/**
 * ExportService
 * Exports recordings as PDF or TXT files
 * 
 * Features:
 * - PDF export with formatting, metadata, timestamps
 * - TXT export as plain text
 * - Tier restrictions: Pro and Max only
 * - Returns file stream for download
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class ExportService {
  /**
   * Export recording as PDF
   * @param {Object} recording - Recording object from database
   * @param {string} outputPath - Where to save the PDF
   * @returns {Promise<string>} - Path to generated PDF
   */
  static async exportPDF(recording, outputPath) {
    return new Promise((resolve, reject) => {
      try {
        // Create PDF document
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 40, left: 40, right: 40, bottom: 40 }
        });

        // Pipe to file
        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // ===== HEADER =====
        doc.fontSize(24).font('Helvetica-Bold').text('MyTranscriber', { align: 'center' });
        doc.fontSize(10).fillColor('#666666').text('Meeting Transcript & Summary', { align: 'center' });
        doc.moveTo(40, doc.y + 5).lineTo(555, doc.y + 5).stroke();
        doc.moveDown();

        // ===== METADATA =====
        doc.fontSize(11).fillColor('#000000').font('Helvetica-Bold').text('Recording Details');
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        
        const createdDate = new Date(recording.created_at).toLocaleString('en-IN', {
          timeZone: 'Asia/Kolkata',
          day: '2-digit',
          month: 'long',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        });

        doc.text(`Title: ${recording.title}`, { continued: false });
        doc.text(`Created: ${createdDate}`);
        doc.text(`Duration: ${this._formatDuration(recording.duration_seconds)}`);
        doc.text(`Tier: ${recording.tier_used.toUpperCase()}`);
        doc.text(`Status: ${recording.status}`);
        doc.moveDown();

        // ===== SUMMARY SECTION =====
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text('Summary');
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        
        const summaryText = this._parseSummary(recording.summary);
        doc.text(summaryText, { align: 'left' });
        doc.moveDown();

        // ===== TRANSCRIPT SECTION =====
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text('Full Transcript');
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        
        const transcriptText = recording.transcript || 'No transcript available.';
        doc.text(transcriptText, { align: 'left', width: 475 });
        doc.moveDown();

        // ===== FOOTER =====
        doc.fontSize(8).fillColor('#999999').text('Generated by MyTranscriber', { align: 'center' });
        doc.text(new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }), { align: 'center' });

        // Finalize PDF
        doc.end();

        stream.on('finish', () => {
          console.log(`✅ PDF exported: ${outputPath}`);
          resolve(outputPath);
        });

        stream.on('error', (err) => {
          reject(new Error(`PDF export failed: ${err.message}`));
        });

      } catch (error) {
        reject(new Error(`PDF generation failed: ${error.message}`));
      }
    });
  }

  /**
   * Export recording as TXT (plain text)
   * @param {Object} recording - Recording object from database
   * @param {string} outputPath - Where to save the TXT
   * @returns {Promise<string>} - Path to generated TXT
   */
  static async exportTXT(recording, outputPath) {
    try {
      const createdDate = new Date(recording.created_at).toLocaleString('en-IN', {
        timeZone: 'Asia/Kolkata',
        day: '2-digit',
        month: 'long',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });

      const content = `
MYTRANSCRIBER - RECORDING EXPORT
═══════════════════════════════════════════════════════════

RECORDING DETAILS:
─────────────────
Title:           ${recording.title}
Created:         ${createdDate}
Duration:        ${this._formatDuration(recording.duration_seconds)}
Tier:            ${recording.tier_used.toUpperCase()}
Status:          ${recording.status}

SUMMARY:
────────
${this._parseSummary(recording.summary)}

FULL TRANSCRIPT:
────────────────
${recording.transcript || 'No transcript available.'}

═══════════════════════════════════════════════════════════
Generated by MyTranscriber
${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}
      `.trim();

      fs.writeFileSync(outputPath, content, 'utf-8');
      console.log(`✅ TXT exported: ${outputPath}`);
      return outputPath;

    } catch (error) {
      throw new Error(`TXT export failed: ${error.message}`);
    }
  }

  /**
   * Parse summary from JSON or plain text
   * @param {string} summary - Summary (JSON or plain text)
   * @returns {string} - Formatted summary text
   */
  static _parseSummary(summary) {
    try {
      const parsed = JSON.parse(summary);
      return parsed.summary || parsed.title || summary;
    } catch (e) {
      return summary || 'No summary available.';
    }
  }

  /**
   * Format duration in seconds to readable string
   * @param {number} seconds - Duration in seconds
   * @returns {string} - Formatted duration (e.g., "1h 23m 45s")
   */
  static _formatDuration(seconds) {
    if (!seconds) return '0s';
    
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;

    const parts = [];
    if (hours > 0) parts.push(`${hours}h`);
    if (minutes > 0) parts.push(`${minutes}m`);
    if (secs > 0) parts.push(`${secs}s`);

    return parts.join(' ');
  }

  /**
   * Check if user tier has export access
   * @param {string} tier - User tier (free/pro/max)
   * @returns {boolean} - true if can export
   */
  static canExport(tier) {
    // Free tier cannot export
    // Pro and Max can export
    return tier === 'pro' || tier === 'max';
  }
}

module.exports = ExportService;